spring:
  application:
    name: account
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        group: SEATA_GROUP
      config:
        server-addr: 127.0.0.1:8848
        file-extension: yml
    alibaba:
      seata:
        tx-service-group: order_tx_group
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/seata_account?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: 123456

server:
  port: 8081


mybatis-plus:
  type-aliases-package: com.wss.account.entity
  mapper-locations:
    - classpath:mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.wss.account.mapper: DEBUG
